### ISSUE TITLE
Questions for consultation

### ISSUE THREAD

**Issue by fygfff** [rishavpramanik/RevTransformerAttentionHAR#1]
X,Y,folds,= DataPreparation(data_input_file)
  avg_acc, avg_recall,avg_f1= Train(X,Y,folds=args.folds,batch_size=args.batch_size,epochs=args.epochs,learning_rate=args.learning_rate)
  ReportAccuracies(avg_acc, avg_recall,avg_f1 )

Should the value of the parameter folds=args. folds be changed to folds??
When I finish modifying and execute the code again

File "G:\yanjiu\lunwen1\erqu\基于 Transformer 的深度反向注意力网络，用于多感官人类活动识别\RevTransformerAttentionHAR-main\main.py", line 21, in <module>
    run(data_input_file)
  File "G:\yanjiu\lunwen1\erqu\基于 Transformer 的深度反向注意力网络，用于多感官人类活动识别\RevTransformerAttentionHAR-main\main.py", line 16, in run
    avg_acc, avg_recall,avg_f1= Train(X,Y,folds=folds,batch_size=args.batch_size,epochs=args.epochs,learning_rate=args.learning_rate)
  File "G:\yanjiu\lunwen1\erqu\基于 Transformer 的深度反向注意力网络，用于多感官人类活动识别\RevTransformerAttentionHAR-main\train.py", line 27, in Train
    model=model_design(img_rows,img_cols,n_class)
  File "G:\yanjiu\lunwen1\erqu\基于 Transformer 的深度反向注意力网络，用于多感官人类活动识别\RevTransformerAttentionHAR-main\utils\model.py", line 37, in model_design
    lay2 = tf.keras.layers.LSTM(32, return_sequences=True)(layer2)
NotImplementedError: Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by rishavpramanik** [comment]
The folds depends how many folds you want to have for cross validation

**Comment by fygfff** [comment]
for i in range(0, len(folds)):
Folds is of type int and has no length
def Train(X,y,folds,batch_size,epochs,learning_rate):
    # Define the number of folds
    avg_acc = []
    avg_recall = []
    avg_f1 = []
    avg_prec=[]
    n_class = y.shape[1]
    _,img_rows, img_cols = X.shape
    for i in range(0, len(folds)):
        train_idx = folds[i][0]
        test_idx = folds[i][1]
        X_train = X[train_idx]
        X_test = X[test_idx]

**Comment by fygfff** [comment]
> 折叠次数取决于交叉验证所需的折叠次数
for i in range(0, len(folds)):
Folds 类型为 int，没有长度
def Train(X,y,folds,batch_size,epochs,learning_rate):
# 定义折叠次数
avg_acc = []
avg_recall = []
avg_f1 = []
avg_prec=[]
n_class = y.shape[1]
_,img_rows, img_cols = X.shape
for i in range(0, len(folds)):
train_idx = folds[i][0]
test_idx = folds[i][1]
X_train = X[train_idx]
X_test = X[test_idx]

**Comment by rishavpramanik** [comment]
args. folds indicate how many folds you need. Whereas the function you did indicate here indices for the train and test split

**Comment by rishavpramanik** [comment]
Thanks for the issue I'm gonna amed the repository for a minor flaw
